### ISSUE TITLE
mapa  mental

### ISSUE THREAD

**Issue by 71santiago7** [SistemasTecTlaxiaco/mapa-mental-71santiago7#2]
[CONJUNTO Y RELACIONES _RENE_SANTIAGO.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-71santiago7/files/7307417/CONJUNTO.Y.RELACIONES._RENE_SANTIAGO.pdf)
[ mapa  mental _ rene_sanriago.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-71santiago7/files/7376834/mapa.mental._.rene_sanriago.pdf)

**Comment by 7177981** [comment]
buen trabajo le doy 85% contiene buena información y cuenta con una buena estructura, falto una mezcla de colores en su diseño

**Comment by josealfredo79** [comment]
Este trabajo esta incompleto, se regresa para nuevamente...rehacerlo...

**Comment by josealfredo79** [comment]
717798 debes checar que el trabajo este completo no es solamente...calificar por calificar...

**Comment by 71santiago7** [comment]
[RENE_SANTIAGO_mapa mental.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-71santiago7/files/7384997/RENE_SANTIAGO_mapa.mental.pdf)

**Comment by 71santiago7** [comment]
> [RENE_SANTIAGO_mapa mental.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-71santiago7/files/7384997/RENE_SANTIAGO_mapa.mental.pdf)
